#!/usr/bin/env bash
#
# Check every commit message in a range against Conventional Commits.
#
# Runs the repo's own commit-msg hook via pre-commit, so .pre-commit-config.yaml
# is the single definition of the rule — the same tool, at the same pinned rev,
# that contributors get locally from `git commit`. A second CI-only linter would
# be a second definition, free to drift from the one people actually feel.
#
# Used by .github/workflows/commit-lint.yml, and runnable locally to check a
# branch before opening a PR:
#
#   .github/scripts/check-commit-messages.sh origin/main HEAD
#
# Merge commits are skipped: "Merge branch 'main' into …" is generated by git and
# is not something a contributor can phrase conventionally.

set -euo pipefail

base="${1:-}"
head="${2:-HEAD}"

# A branch's first push — and some force-pushes — report an all-zero "before"
# sha, which names no commit. There is no range to walk in that case, so fall
# back to the tip commit alone rather than failing on a bad revision.
if [ -n "$base" ] && git rev-parse --verify --quiet "${base}^{commit}" >/dev/null; then
  revs=$(git rev-list --no-merges "${base}..${head}")
else
  revs=$(git rev-list --no-merges -1 "${head}")
fi

msg_file=$(mktemp)
trap 'rm -f "$msg_file"' EXIT

checked=0
failed=0
while IFS= read -r sha; do
  [ -n "$sha" ] || continue
  checked=$((checked + 1))
  git log -1 --format=%B "$sha" > "$msg_file"
  if ! pre-commit run conventional-pre-commit \
    --hook-stage commit-msg --commit-msg-filename "$msg_file"; then
    # pre-commit prints the offending subject but not which commit it came from.
    git log -1 --format='       in %h (%an, %ad)' --date=short "$sha" >&2
    failed=$((failed + 1))
  fi
done <<< "$revs"

echo "checked $checked commit message(s)"

if [ "$failed" -gt 0 ]; then
  echo "error: $failed commit message(s) do not follow Conventional Commits" >&2
  echo "hint: install the hook locally so this fails at commit time:" >&2
  echo "      pre-commit install" >&2
  exit 1
fi
